os: Visual Studio 2015
platform:
  - x64

configuration:
  - Debug
  - Release
  
environment:
  INTR_QTDIR: "C:\\Qt\\5.7\\msvc2015_64\\"
  INTR_GIT_TOKEN: 
    secure: 3K1IRVqC1dSplGBGvUMuykBbCMIH8INr3HUE4YNJDmtEYNy0kTJPzeW+pMSCae4y
  VK_SDK_PATH: "C:\\VulkanSDK\\1.0.46.0\\"
  
artifacts:
  - path: Intrinsic_Win32.7z
    name: Intrinsic_Win32
    
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token: $(INTR_GIT_TOKEN)
  artifact: Intrinsic_Win32
  draft: false
  prerelease: false
  on:
    configuration: Release
    branch: master
    appveyor_repo_tag: true

install:
  - cd ..
  - git clone https://%INTR_GIT_TOKEN%@github.com/begla/Intrinsic_Dependencies.git
  - cd Intrinsic
  - cd scripts_win32
  - call ConfigAndBuildDependencies.bat
  - cd ..
  
# Download and install Vulkan SDK
  - appveyor DownloadFile https://vulkan.lunarg.com/sdk/download/1.0.46.0/windows/VulkanSDK-1.0.46.0-Installer.exe -FileName vulkan.exe
  - vulkan.exe /S

build_script:
  - dir
  - cd scripts_win32
  - call Config.bat
  - cd ../build
  - cmake --build . --config %CONFIGURATION%
  - cd ..
# Create artifacts only for tags and release configuration
  - ps: |
        if ($env:APPVEYOR_REPO_TAG -eq $true -And $env:CONFIGURATION -eq "Release")
        {
          cd scripts_win32
          & .\CopyDllsToAppDir_Release.bat
          & .\DistroCreateAndZip.bat
        }
