language: cpp
sudo: required
dist: trusty

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-4.0
    packages:
        - cmake
        - cmake-data
        - ninja-build
        - clang-4.0
        - gcc-6
        - g++-6
env:
  matrix:
    # GCC
    - MATRIX_EVAL="CC=/usr/bin/gcc-6 && CXX=/usr/bin/g++-6"
      CMAKE_BUILD_TYPE="Debug"
    - MATRIX_EVAL="CC=/usr/bin/gcc-6 && CXX=/usr/bin/g++-6"
      CMAKE_BUILD_TYPE="Release"
    # Clang
    - MATRIX_EVAL="CC=/usr/bin/clang-4.0 && CXX=/usr/bin/clang++-4.0"
      CMAKE_BUILD_TYPE="Debug"
    - MATRIX_EVAL="CC=/usr/bin/clang-4.0 && CXX=/usr/bin/clang++-4.0"
      CMAKE_BUILD_TYPE="Release"

before_install:
  - eval "${MATRIX_EVAL}"

# Clone private dependencies which are not part of the main repository
  - cd ..
  - git clone https://$INTR_GIT_TOKEN@github.com/begla/Intrinsic_Dependencies.git
  - cd Intrinsic
  
install:
# SDL2
  - curl -O http://libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - (cd SDL2-2.0.5 && ./configure && make && sudo make install)
  
# Vulkan SDK
  - curl https://vulkan.lunarg.com/sdk/download/1.0.51.0/linux/vulkansdk-linux-x86_64-1.0.51.0.run -L -o vulkan.run
  - chmod +x vulkan.run
  - ./vulkan.run
  
# Build dependencies
  - cd scripts_linux
  - chmod +x ConfigAndBuildDependencies
  - ./ConfigAndBuildDependencies
  - cd ..
  
script:
  - export VK_SDK_PATH=$(pwd)/VulkanSDK/1.0.51.0/x86_64/

# Build
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - cmake --build .
