language: cpp
sudo: required

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - gcc-6
      - g++-6
      - libc6

compiler:
  - gcc

before_install:
# Setup GCC 6 as the default compiler
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
  - gcc --version
# Clone private dependencies which are not part of the main repository
  - cd ..
  - git clone https://$INTR_GIT_TOKEN@github.com/begla/Intrinsic_Dependencies.git
  - cd Intrinsic
  
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  
install:
# SDL2
  - curl -O http://libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - (cd SDL2-2.0.5 && ./configure && make && sudo make install)
  
# Vulkan SDK
  - curl https://vulkan.lunarg.com/sdk/download/1.0.30.0/linux/vulkansdk-linux-x86_64-1.0.30.0.run -L -o vulkan.run
  - chmod +x vulkan.run
  - ./vulkan.run
  
# Build dependencies
  - cd scripts_linux
  - chmod +x ConfigAndBuildDependencies
  - ./ConfigAndBuildDependencies
  - cd ..
  
script:
  - export VK_SDK_PATH=$(pwd)/VulkanSDK/1.0.30.0/x86_64/
  
# Check all env. variables
  - printenv

# Config via CMake
  - cd scripts_linux
  - chmod +x Config_Release Build
  - ./Config_Release
  - ./Build
  - cd ..
